{
 "title": "POD性能",
 "tags": [ "POD性能" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(container_last_seen,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(container_last_seen{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(container_last_seen{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(container_last_seen{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "服务连续运行时间",
   "type": "graph",
   "description": "服务连续运行时间",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{instance=~\"$instance\",pod_name=~\".+\",image!=\"\"}",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "cpu使用率",
   "type": "graph",
   "description": "cpu使用率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{instance=~\"$instance\",pod_name=~\".+\",image!=\"\"}[5m]) ",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "graph",
   "description": "内存使用",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=~\"$instance\",pod_name=~\".+\",image!=\"\"}",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "磁盘写速率",
   "type": "graph",
   "description": "磁盘写速率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{instance=~\"$instance\",image!=\"\"}[5m])",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "磁盘读速率",
   "type": "graph",
   "description": "磁盘读速率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{instance=~\"$instance\",pod_name=~\".+\",image!=\"\"}[5m])",
     "legendFormat": "{{namespace}}/{{pod_name}}({{device}})"
    }
   ]
  },
  {
   "title": "网卡发送速率",
   "type": "graph",
   "description": "网卡发送速率",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{instance=~\"$instance\",pod_name=~\".+\",container_name=\"POD\"}[5m])",
     "legendFormat": "{{namespace}}/{{pod_name}}({{interface}})"
    }
   ]
  },
  {
   "title": "网卡接收速率",
   "type": "graph",
   "description": "网卡接收速率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{instance=~\"$instance\",pod_name=~\".+\",container_name=\"POD\"}[5m])",
     "legendFormat": "{{namespace}}/{{pod_name}}({{interface}})"
    }
   ]
  }
 ]
}