{
 "title": "RabbitMQ",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(rabbitmq_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(rabbitmq_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(rabbitmq_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "label_values(rabbitmq_exporter_build_info{minor=~'$minor'},instance)"
   },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rabbitmq_running{node=\"$node\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{instance=~\"$ip\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~\"$ip\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~\"$ip\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "Connections, channels and consumers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{instance=~\"$ip\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "rabbitmq_channels{instance=~\"$ip\"}",
     "legendFormat": "channels"
    },
    {
     "expr": "rabbitmq_consumers{instance=~\"$ip\"}",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_disk_free", "legendFormat": "{{node}}:free" },
    { "expr": "rabbitmq_node_disk_free_limit", "legendFormat": "{{node}}:limit" }
   ]
  }
 ]
}