{
 "title": "cpu使用率",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu使用率异常检测",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "异常",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_used_percent",
     "query": "SELECT \"difference\" FROM \"cpu_used_percent\" WHERE (\"instance\" =~ /^$instance$/ AND \"major\" =~ /^$major$/ AND \"minor\" =~ /^$minor$/ AND \"vip\" =~ /^$vip$/) AND $timeFilter GROUP BY \"instance\", \"major\", \"minor\", \"vip\"",
     "select": [
      [
       { "params": [ "difference" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "expr": "100 - (avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"idle\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "cpu使用率",
   "type": "graph",
   "description": "## cpu使用率 ##",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"idle\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    },
    {}
   ]
  },
  {
   "title": "cpu使用率预测",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_used_percent",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vip", "operator": "=~", "value": "/^$vip$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_used_percent",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vip", "operator": "=~", "value": "/^$vip$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "100 - (avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"idle\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "cpu system使用率",
   "type": "graph",
   "description": "cpu system使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"system\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu system使用率预测",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_system",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vip", "operator": "=~", "value": "/^$vip$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_system",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vip", "operator": "=~", "value": "/^$vip$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"system\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "cpu user使用率",
   "type": "graph",
   "description": "cpu user使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"user\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu user使用率预测",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_user",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_user",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"user\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "cpu nice使用率",
   "type": "graph",
   "description": "cpu nice使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"nice\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu softirq使用率",
   "type": "graph",
   "description": "cpu 软中断使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"softirq\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu softirq使用率预测",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_softirq",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_softirq",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"softirq\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "cpu iowait使用率",
   "type": "graph",
   "description": "cpu iowait使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"iowait\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu steal使用率",
   "type": "graph",
   "description": "cpu steal 使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"steal\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu idle使用率",
   "type": "graph",
   "description": "cpu idle使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"idle\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cpu idle使用率预测",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_idle",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "cpu_idle",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"idle\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "cpu irq使用率",
   "type": "graph",
   "description": "cpu irq使用率",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (vip,major,minor,instance) (irate(node_cpu_seconds_total{mode=\"irq\",vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])) * 100)",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  }
 ]
}