{
 "title": "tcp 连接数",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "网络establish数",
   "type": "graph",
   "description": "网络establish数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": " SYN-SENT平均连接数",
   "type": "graph",
   "description": " SYN-SENT平均连接数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "已经分配读网络连接数",
   "type": "graph",
   "description": "已经分配读网络连接数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "udp inuse 连接数",
   "type": "graph",
   "description": "udp inuse连接数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDP_inuse{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "socket timewait数",
   "type": "graph",
   "description": "socket timewait数",
   "gridPos": { "h": 9, "w": 23, "x": 1, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "正在侦听的TCP套接字数量",
   "type": "graph",
   "description": "TCP_inuse - 正在使用（正在侦听）的TCP套接字数量",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "SYN-RCVD平均连接数",
   "type": "graph",
   "description": "SYN-RCVD平均连接数",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "tcp inused连接数",
   "type": "graph",
   "description": "tcp  inused连接数",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  }
 ]
}