{
 "title": "vmstat",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "磁盘读速率",
   "type": "graph",
   "description": "磁盘读速率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘写速率",
   "type": "graph",
   "description": "磁盘写速率",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘读iops",
   "type": "graph",
   "description": "磁盘读iops",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{ instance }}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘写iops",
   "type": "graph",
   "description": "磁盘写iops",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "description": "磁盘使用率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',fstype=~\"ext4|xfs|overlay\",mountpoint=\"/\"} / node_filesystem_size_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',fstype=~\"ext4|xfs|overlay\",mountpoint=\"/\"})",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/mount={{mountpoint}}"
    }
   ]
  }
 ]
}