{
 "title": "内存使用率",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "内存总量",
   "type": "graph",
   "description": "内存总量",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "description": "## 内存使用率 ##",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (vip,major,minor,instance) (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m]) + avg_over_time(node_memory_Cached_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m]) + avg_over_time(node_memory_Buffers_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m])) / avg_over_time(node_memory_MemTotal_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m]))))  ",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率预测",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "mem_used_percent",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" }
     ],
     "measurement": "mem_used_percent",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" }
     ]
    },
    {
     "expr": "sum by (vip,major,minor,instance) (100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m]) + avg_over_time(node_memory_Cached_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m]) + avg_over_time(node_memory_Buffers_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m])) / avg_over_time(node_memory_MemTotal_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[1m]))))  ",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "可用内存",
   "type": "graph",
   "description": "可用内存",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "剩余内存",
   "type": "graph",
   "description": "剩余内存",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "cache内存",
   "type": "graph",
   "description": "cache内存",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "Buffer内存",
   "type": "graph",
   "description": "Buffer内存",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "Shmem内存",
   "type": "graph",
   "description": "Shmem内存",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Shmem_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "slab内存",
   "type": "graph",
   "description": "slab内存",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Slab_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "inactive内存",
   "type": "graph",
   "description": "inactive内存",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "Active内存",
   "type": "graph",
   "description": "Active内存",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "Dirty内存",
   "type": "graph",
   "description": "Dirty内存",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "KernelStack内存",
   "type": "graph",
   "description": "KernelStack内存",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  }
 ]
}