{
 "title": "磁盘IO性能",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(node_disk_read_bytes_total{instance=~'$instance'},device)"
   }
  ]
 },
 "panels": [
  {
   "title": "磁盘读速率",
   "type": "graph",
   "description": "磁盘读速率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘读预测",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "上界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk_read_bytes",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "下界",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "major" ], "type": "tag" },
      { "params": [ "minor" ], "type": "tag" },
      { "params": [ "vip" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk_read_bytes",
     "query": "SELECT \"lower\" FROM \"disk_write_bytes\" WHERE (\"instance\" =~ /^$instance$/ AND \"major\" =~ /^$major$/ AND \"minor\" =~ /^$minor$/ AND \"vip\" =~ /^$vip$/ AND \"device\" =~ /^$device$/) AND $timeFilter GROUP BY \"instance\", \"major\", \"minor\", \"vip\", \"device\"",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "major", "operator": "=~", "value": "/^$major$/" },
      { "condition": "AND", "key": "minor", "operator": "=~", "value": "/^$minor$/" },
      { "condition": "AND", "key": "vip", "operator": "=~", "value": "/^$vip$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "expr": "irate(node_disk_read_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',device=~'$device'}[5m])",
     "legendFormat": "真实值"
    }
   ]
  },
  {
   "title": "磁盘写速率",
   "type": "graph",
   "description": "磁盘写速率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘写iops",
   "type": "graph",
   "description": "磁盘写iops",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘读iops",
   "type": "graph",
   "description": "磁盘读iops",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{ instance }}/device={{device}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "description": "磁盘使用率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',fstype=~\"ext4|xfs|overlay\",mountpoint=\"/\"} / node_filesystem_size_bytes{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',fstype=~\"ext4|xfs|overlay\",mountpoint=\"/\"})",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/mount={{mountpoint}}"
    }
   ]
  }
 ]
}