{
 "title": "系统负载",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "1min负载",
   "type": "graph",
   "description": "1min负载",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "5分钟负载",
   "type": "graph",
   "description": "5分钟负载",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load5{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  },
  {
   "title": "15分钟负载",
   "type": "graph",
   "description": "15分钟负载",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load15{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},instance={{instance}}"
    }
   ]
  }
 ]
}