{
 "title": "网络性能",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,vip)"
   },
   {
    "name": "major",
    "label": "版本",
    "query": "label_values(node_exporter_build_info{vip=~'$vip'},major)"
   },
   {
    "name": "minor",
    "label": "次版本",
    "query": "label_values(node_exporter_build_info{major=~'$major'},minor)"
   },
   {
    "name": "instance",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{minor=~'$minor'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "接收包速率",
   "type": "graph",
   "description": "接收包速率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "发送包速率",
   "type": "graph",
   "description": "发送包速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "接收缓冲区溢出的错误速率",
   "type": "graph",
   "description": "接收缓冲区溢出的错误速率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "发送缓冲区溢出错误速率",
   "type": "graph",
   "description": "发送缓冲区溢出错误速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_fifo_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "网卡接收错误速率",
   "type": "graph",
   "description": "网卡接收错误速率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "网卡发送错误速率",
   "type": "graph",
   "description": "网卡发送错误速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "接收丢包数率",
   "type": "graph",
   "description": "接收丢包数率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "发送丢包速率",
   "type": "graph",
   "description": "发送丢包速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_drop_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "接收压缩字节速率",
   "type": "graph",
   "description": "接收压缩字节速率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "发送压缩包速率",
   "type": "graph",
   "description": "发送压缩包速率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_compressed_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance'}[5m])",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "网卡流出速率",
   "type": "graph",
   "description": "网卡流出速率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*|tun.*|dummy.*|kube.*'}[5m])*8",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  },
  {
   "title": "网卡流入速率",
   "type": "graph",
   "description": "网卡流入速率",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{vip =~'$vip',major=~'$major',minor=~'$minor',instance=~'$instance',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|cali.*|tun.*|dummy.*|kube.*'}[5m])*8",
     "legendFormat": "vip={{vip}},major={{major}},minor={{minor}},{{instance}}/device={{device}}"
    }
   ]
  }
 ]
}